version: '3.3'
services:
  app:
    environment:
        TZ: "CET"
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      - db_container
    command: mvn clean install spring-boot:run

  db_container:
    container_name: db_container
    image: mysql/mysql-server:5.7
    environment:
      TZ: "CET"
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
